services:
  - type: web
    name: github-vercel-deployer
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: github-vercel-deployer
          property: port
